# TCL File Generated by Component Editor 18.1
# Tue Mar 21 11:07:29 CST 2023
# DO NOT MODIFY


# 
# vhdmi "vhdmi" v1.0
#  2023.03.21.11:07:29
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module vhdmi
# 
set_module_property DESCRIPTION ""
set_module_property NAME vhdmi
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME vhdmi
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL receive_top
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file vhdmi.qxp QXP PATH vhdmi.qxp


# 
# parameters
# 
add_parameter BUF1_BASE_ADDR INTEGER 0
set_parameter_property BUF1_BASE_ADDR DEFAULT_VALUE 0
set_parameter_property BUF1_BASE_ADDR DISPLAY_NAME BUF1_BASE_ADDR
set_parameter_property BUF1_BASE_ADDR TYPE INTEGER
set_parameter_property BUF1_BASE_ADDR UNITS None
set_parameter_property BUF1_BASE_ADDR ALLOWED_RANGES -2147483648:2147483647
set_parameter_property BUF1_BASE_ADDR HDL_PARAMETER true
add_parameter BUF2_BASE_ADDR INTEGER 384000 ""
set_parameter_property BUF2_BASE_ADDR DEFAULT_VALUE 384000
set_parameter_property BUF2_BASE_ADDR DISPLAY_NAME BUF2_BASE_ADDR
set_parameter_property BUF2_BASE_ADDR WIDTH ""
set_parameter_property BUF2_BASE_ADDR TYPE INTEGER
set_parameter_property BUF2_BASE_ADDR UNITS None
set_parameter_property BUF2_BASE_ADDR ALLOWED_RANGES -2147483648:2147483647
set_parameter_property BUF2_BASE_ADDR DESCRIPTION ""
set_parameter_property BUF2_BASE_ADDR HDL_PARAMETER true


# 
# display items
# 


# 
# connection point s_avalon_mm
# 
add_interface s_avalon_mm avalon end
set_interface_property s_avalon_mm addressUnits WORDS
set_interface_property s_avalon_mm associatedClock clk_hps
set_interface_property s_avalon_mm associatedReset rst_n
set_interface_property s_avalon_mm bitsPerSymbol 8
set_interface_property s_avalon_mm burstOnBurstBoundariesOnly false
set_interface_property s_avalon_mm burstcountUnits WORDS
set_interface_property s_avalon_mm explicitAddressSpan 0
set_interface_property s_avalon_mm holdTime 0
set_interface_property s_avalon_mm linewrapBursts false
set_interface_property s_avalon_mm maximumPendingReadTransactions 0
set_interface_property s_avalon_mm maximumPendingWriteTransactions 0
set_interface_property s_avalon_mm readLatency 0
set_interface_property s_avalon_mm readWaitTime 1
set_interface_property s_avalon_mm setupTime 0
set_interface_property s_avalon_mm timingUnits Cycles
set_interface_property s_avalon_mm writeWaitTime 0
set_interface_property s_avalon_mm ENABLED true
set_interface_property s_avalon_mm EXPORT_OF ""
set_interface_property s_avalon_mm PORT_NAME_MAP ""
set_interface_property s_avalon_mm CMSIS_SVD_VARIABLES ""
set_interface_property s_avalon_mm SVD_ADDRESS_GROUP ""

add_interface_port s_avalon_mm s_avl_wr_req write Input 1
add_interface_port s_avalon_mm s_avl_rd_req read Input 1
add_interface_port s_avalon_mm s_avl_wr_data writedata Input 32
add_interface_port s_avalon_mm s_avl_rd_data readdata Output 32
add_interface_port s_avalon_mm s_avl_address address Input 8
add_interface_port s_avalon_mm s_avl_chipselect chipselect Input 1
set_interface_assignment s_avalon_mm embeddedsw.configuration.isFlash 0
set_interface_assignment s_avalon_mm embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s_avalon_mm embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s_avalon_mm embeddedsw.configuration.isPrintableDevice 0


# 
# connection point m_avalon_mm
# 
add_interface m_avalon_mm avalon start
set_interface_property m_avalon_mm addressUnits SYMBOLS
set_interface_property m_avalon_mm associatedClock clk_hps
set_interface_property m_avalon_mm associatedReset rst_n
set_interface_property m_avalon_mm bitsPerSymbol 8
set_interface_property m_avalon_mm burstOnBurstBoundariesOnly false
set_interface_property m_avalon_mm burstcountUnits WORDS
set_interface_property m_avalon_mm doStreamReads false
set_interface_property m_avalon_mm doStreamWrites false
set_interface_property m_avalon_mm holdTime 0
set_interface_property m_avalon_mm linewrapBursts false
set_interface_property m_avalon_mm maximumPendingReadTransactions 0
set_interface_property m_avalon_mm maximumPendingWriteTransactions 0
set_interface_property m_avalon_mm readLatency 0
set_interface_property m_avalon_mm readWaitTime 1
set_interface_property m_avalon_mm setupTime 0
set_interface_property m_avalon_mm timingUnits Cycles
set_interface_property m_avalon_mm writeWaitTime 0
set_interface_property m_avalon_mm ENABLED true
set_interface_property m_avalon_mm EXPORT_OF ""
set_interface_property m_avalon_mm PORT_NAME_MAP ""
set_interface_property m_avalon_mm CMSIS_SVD_VARIABLES ""
set_interface_property m_avalon_mm SVD_ADDRESS_GROUP ""

add_interface_port m_avalon_mm m_avl_addr address Output 32
add_interface_port m_avalon_mm m_avl_be byteenable Output 16
add_interface_port m_avalon_mm m_avl_size burstcount Output 8
add_interface_port m_avalon_mm m_avl_wdata writedata Output 128
add_interface_port m_avalon_mm m_avl_write_req write Output 1
add_interface_port m_avalon_mm m_avl_waitrequest waitrequest Input 1


# 
# connection point rst_n
# 
add_interface rst_n reset end
set_interface_property rst_n associatedClock clk_hps
set_interface_property rst_n synchronousEdges DEASSERT
set_interface_property rst_n ENABLED true
set_interface_property rst_n EXPORT_OF ""
set_interface_property rst_n PORT_NAME_MAP ""
set_interface_property rst_n CMSIS_SVD_VARIABLES ""
set_interface_property rst_n SVD_ADDRESS_GROUP ""

add_interface_port rst_n rst_n reset_n Input 1


# 
# connection point vga_in
# 
add_interface vga_in conduit end
set_interface_property vga_in associatedClock clk_hps
set_interface_property vga_in associatedReset rst_n
set_interface_property vga_in ENABLED true
set_interface_property vga_in EXPORT_OF ""
set_interface_property vga_in PORT_NAME_MAP ""
set_interface_property vga_in CMSIS_SVD_VARIABLES ""
set_interface_property vga_in SVD_ADDRESS_GROUP ""

add_interface_port vga_in vga_clk vga_clk Input 1
add_interface_port vga_in vga_de vga_de Input 1
add_interface_port vga_in vga_hsync vga_hsync Input 1
add_interface_port vga_in vga_vsync vga_vsync Input 1
add_interface_port vga_in vga_rgb vga_rgb Input 24


# 
# connection point clk_hps
# 
add_interface clk_hps clock end
set_interface_property clk_hps clockRate 0
set_interface_property clk_hps ENABLED true
set_interface_property clk_hps EXPORT_OF ""
set_interface_property clk_hps PORT_NAME_MAP ""
set_interface_property clk_hps CMSIS_SVD_VARIABLES ""
set_interface_property clk_hps SVD_ADDRESS_GROUP ""

add_interface_port clk_hps clk_hps clk Input 1

